/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'twer' at '7/19/15 9:56 PM' with Gradle 2.2.1
 *
 * @author twer, @date 7/19/15 9:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
